// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyCWG23oVt03reCE4s1ZJyj27XBogWBZnWE",
    authDomain: "monitorapp-881da.firebaseapp.com",
    projectId: "monitorapp-881da",
    storageBucket: "monitorapp-881da.firebasestorage.app",
    messagingSenderId: "110511576078",
    appId: "1:110511576078:web:803a78c63e362d5116d85f",
    measurementId: "G-6C2L50LXWT",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyCWG23oVt03reCE4s1ZJyj27XBogWBZnWE",
    authDomain: "monitorapp-881da.firebaseapp.com",
    projectId: "monitorapp-881da",
    storageBucket: "monitorapp-881da.firebasestorage.app",
    messagingSenderId: "110511576078",
    appId: "1:110511576078:web:803a78c63e362d5116d85f",
    measurementId: "G-6C2L50LXWT",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyCWG23oVt03reCE4s1ZJyj27XBogWBZnWE",
    authDomain: "monitorapp-881da.firebaseapp.com",
    projectId: "monitorapp-881da",
    storageBucket: "monitorapp-881da.firebasestorage.app",
    messagingSenderId: "110511576078",
    appId: "1:110511576078:web:803a78c63e362d5116d85f",
    measurementId: "G-6C2L50LXWT",
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: "AIzaSyCWG23oVt03reCE4s1ZJyj27XBogWBZnWE",
    authDomain: "monitorapp-881da.firebaseapp.com",
    projectId: "monitorapp-881da",
    storageBucket: "monitorapp-881da.firebasestorage.app",
    messagingSenderId: "110511576078",
    appId: "1:110511576078:web:803a78c63e362d5116d85f",
    measurementId: "G-6C2L50LXWT",
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: "AIzaSyCWG23oVt03reCE4s1ZJyj27XBogWBZnWE",
    authDomain: "monitorapp-881da.firebaseapp.com",
    projectId: "monitorapp-881da",
    storageBucket: "monitorapp-881da.firebasestorage.app",
    messagingSenderId: "110511576078",
    appId: "1:110511576078:web:803a78c63e362d5116d85f",
    measurementId: "G-6C2L50LXWT",
  );
}
