// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyCczhiti7hwlHqwPH7eYhR5F5kgkuj4P-U",
    authDomain: "tracker-785f3.firebaseapp.com",
    projectId: "tracker-785f3",
    storageBucket: "tracker-785f3.firebasestorage.app",
    messagingSenderId: "268379069586",
    appId: "1:268379069586:web:0ed6720d078466ff001a4b",
    measurementId: "G-MM731337B6",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyCczhiti7hwlHqwPH7eYhR5F5kgkuj4P-U",
    authDomain: "tracker-785f3.firebaseapp.com",
    projectId: "tracker-785f3",
    storageBucket: "tracker-785f3.firebasestorage.app",
    messagingSenderId: "268379069586",
    appId: "1:268379069586:web:0ed6720d078466ff001a4b",
    measurementId: "G-MM731337B6",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyCczhiti7hwlHqwPH7eYhR5F5kgkuj4P-U",
    authDomain: "tracker-785f3.firebaseapp.com",
    projectId: "tracker-785f3",
    storageBucket: "tracker-785f3.firebasestorage.app",
    messagingSenderId: "268379069586",
    appId: "1:268379069586:web:0ed6720d078466ff001a4b",
    measurementId: "G-MM731337B6",
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: "AIzaSyCczhiti7hwlHqwPH7eYhR5F5kgkuj4P-U",
    authDomain: "tracker-785f3.firebaseapp.com",
    projectId: "tracker-785f3",
    storageBucket: "tracker-785f3.firebasestorage.app",
    messagingSenderId: "268379069586",
    appId: "1:268379069586:web:0ed6720d078466ff001a4b",
    measurementId: "G-MM731337B6",
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: "AIzaSyCczhiti7hwlHqwPH7eYhR5F5kgkuj4P-U",
    authDomain: "tracker-785f3.firebaseapp.com",
    projectId: "tracker-785f3",
    storageBucket: "tracker-785f3.firebasestorage.app",
    messagingSenderId: "268379069586",
    appId: "1:268379069586:web:0ed6720d078466ff001a4b",
    measurementId: "G-MM731337B6",
  );
}
